#!/bin/bash

jwtSecret=$(cat /dev/urandom | base64 | head -c 256)

if [ -z "$POSTGRES_PASSWORD" ]; then
  echo "POSTGRES_PASSWORD not set, generating a new one"
  POSTGRES_PASSWORD=$(cat /dev/urandom | base64 | head -c 64)
fi

if [ -z "$ENCRYPTION_KEY" ]; then
  echo "ENCRYPTION_KEY not set, generating a new one"
  ENCRYPTION_KEY=$(cat /dev/urandom | base64 | head -c 64)
fi

if [ -z "$RETOOL_LICENSE_KEY" ]; then
  echo "RETOOL_LICENSE_KEY not set, using trial license key"
  RETOOL_LICENSE_KEY=EXPIRED-LICENSE-KEY-TRIAL
fi

if [ -f ./docker.env ]; then
  mv docker.env docker.env.$(date +"%Y-%m-%d_%H-%M-%S")
fi
touch docker.env

echo '## For a complete list of all environment variables, see docs.retool.com/docs/environment-variables' >> docker.env
echo '' >> docker.env

echo '## Set node environment to production' >> docker.env
echo 'NODE_ENV=production' >> docker.env
echo '' >> docker.env
echo '## Set the JWT secret for the API server' >> docker.env
echo "JWT_SECRET=\"${jwtSecret}\"" >> docker.env
echo '' >> docker.env

echo '## Set and generate postgres credentials' >> docker.env
echo 'POSTGRES_DB=hammerhead_production' >> docker.env
echo 'POSTGRES_USER=retool_internal_user' >> docker.env
echo 'POSTGRES_HOST=postgres' >> docker.env
echo 'POSTGRES_PORT=5432' >> docker.env
echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> docker.env
echo '' >> docker.env

echo '## Used to create links for your users, like new user invitations and forgotten password resets' >> docker.env
echo '## The backend tries to guess this, but it can be incorrect if there’s a proxy in front of the website' >> docker.env
echo '# BASE_DOMAIN=https://retool.yourwebsite.com' >> docker.env
echo '' >> docker.env

echo '## Set key to encrypt and decrypt database passwords, etc.' >> docker.env
echo "ENCRYPTION_KEY=${ENCRYPTION_KEY}" >> docker.env
echo '' >> docker.env

echo "## Google SSO configuration" >> docker.env
echo "# CLIENT_ID={YOUR GOOGLE CLIENT ID}" >> docker.env
echo '' >> docker.env

echo '## License key' >> docker.env
echo "LICENSE_KEY=${RETOOL_LICENSE_KEY}" >> docker.env
echo '' >> docker.env

echo '## Uncomment this line if HTTPS is not set up' >> docker.env
echo 'COOKIE_INSECURE=true' >> docker.env 

echo "Cool! Now add your license key in docker.env then run docker-compose up to launch Retool."
